from flask import Flask, jsonify, render_template_string
import os, sqlite3
from evaluator import evaluate_real
app=Flask(__name__); DB_PATH=os.getenv('DB_PATH','bot_sismico.db')
def db():
    c=sqlite3.connect(DB_PATH); c.row_factory=sqlite3.Row; return c
def rows(q,a=()):
    with db() as c:return [dict(x) for x in c.execute(q,a).fetchall()]
def scalar(q):
    with db() as c:
        x=c.execute(q).fetchone(); return x[0] if x else 0
@app.get('/api/dashboard')
def api_dashboard():
    es=rows("SELECT * FROM observed_events WHERE source='CSN' ORDER BY occurred_at DESC")
    ps=rows("SELECT * FROM real_predictions ORDER BY group_name,prediction_no")
    results=[]; groups={}
    for p in ps:
        st,b,rad,_=evaluate_real(p,es); m=None
        if b:
            e=dict(b['e']); center=(p['mag_min']+p['mag_max'])/2
            m={'event':e,'distance_km':round(b['dist'],3),'delta_mag':round(abs(e['magnitude']-center),3),'time_ok':b['t'],'mag_ok':b['m'],'geo_ok':b['g']}
        results.append({'code':p['code'],'group':p['group_name'],'status':st,'radius':rad,'prediction':p,'match':m})
        g=groups.setdefault(p['group_name'],{'group':p['group_name'],'hits':0,'misses':0,'pending':0}); g['hits' if st=='ACERTADA' else 'misses' if st=='NO ACERTADA' else 'pending']+=1
    for g in groups.values():
        n=g['hits']+g['misses']; g['accuracy']=round(100*g['hits']/n,1) if n else None
    hits=sum(r['status']=='ACERTADA' for r in results)
    return jsonify({'stats':{'predictions':len(ps),'events':len(es),'hits':hits,'correlations':hits,'pending':sum(r['status']=='PENDIENTE' for r in results),'misses':sum(r['status']=='NO ACERTADA' for r in results),'history_records':scalar('SELECT COUNT(*) FROM correlation_history')},'events':es[:100],'results':results,'ranking':sorted(groups.values(),key=lambda x:(x['accuracy'] if x['accuracy'] is not None else -1,x['hits']),reverse=True)})
HTML='''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sismologia Lab v1.5</title><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
:root{--bg:#07111f;--card:#0e1c2e;--line:#20344d;--text:#eaf2ff;--muted:#8ea4bd;--cyan:#42d9ff;--green:#56e39f;--yellow:#ffd166;--red:#ff667a}*{box-sizing:border-box}body{margin:0;background:#07111f;color:var(--text);font:14px system-ui}.wrap{max-width:1450px;margin:auto;padding:22px}.top{display:flex;justify-content:space-between}.muted{color:var(--muted)}.live{color:var(--green);font-weight:800}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:15px;padding:15px}.metric b{font-size:27px;display:block;margin-top:7px}.main{display:grid;grid-template-columns:1.65fr 1fr;gap:12px;margin-top:12px}#map{height:590px;border-radius:10px}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.controls select,.controls button{background:#15283e;color:white;border:1px solid var(--line);padding:8px;border-radius:8px}.controls label{padding:7px}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:8px;border-bottom:1px solid var(--line);text-align:left}.scroll{max-height:450px;overflow:auto}.result{padding:10px;border:1px solid var(--line);border-radius:10px;margin:7px 0;cursor:pointer}.result:hover{border-color:var(--cyan)}a{color:var(--cyan)}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}.main{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div><h1>🌎 SISMOLOGIA LAB v1.5</h1><div class="muted">Evaluador único Discord + Web · Inspector + mapa avanzado</div></div><div class="live">● EN LÍNEA</div></div><div class="grid"><div class="card metric">🎯 Predicciones<b id="pred">—</b></div><div class="card metric">🌎 CSN<b id="events">—</b></div><div class="card metric">✅ Aciertos<b id="hits">—</b></div><div class="card metric">🟡 Pendientes<b id="pending">—</b></div><div class="card metric">❌ Fallidas<b id="misses">—</b></div><div class="card metric">🚨 Coincidencias 3/3<b id="corrs">—</b></div></div>
<div class="main"><div class="card"><h2>🗺️ Mapa de Chile</h2><div class="controls"><select id="ia"><option value="">Todas las IA</option></select><select id="st"><option value="">Todos los estados</option><option>ACERTADA</option><option>PENDIENTE</option><option>NO ACERTADA</option></select><label><input id="rad" type="checkbox" checked> Radios</label><label><input id="lin" type="checkbox" checked> Conexiones</label><label><input id="only" type="checkbox"> Solo coincidencias</label><button onclick="map.setView([-33.45,-70.65],5)">🇨🇱 Centrar Chile</button></div><div class="muted">🔴 sismo · 🔵 pendiente · 🟢 acertada · ⚫ fallida</div><div id="map"></div></div><div class="card"><h2>🏆 Ranking</h2><table class="table"><thead><tr><th>IA</th><th>✅</th><th>❌</th><th>🟡</th><th>%</th></tr></thead><tbody id="rank"></tbody></table><h2>🔎 Inspector</h2><div id="inspect" class="muted">Haz clic en una predicción.</div></div></div>
<div class="main"><div class="card"><h2>🎯 Predicciones evaluadas</h2><div id="results" class="scroll"></div></div><div class="card"><h2>🌎 Últimos sismos</h2><table class="table"><tbody id="quakes"></tbody></table><p class="muted">Registros históricos de alertas: <b id="hist">—</b>. Este contador puede ser menor que los aciertos; el resultado oficial es el del evaluador 3/3.</p></div></div><p class="muted">⚠️ Experimento de evaluación; no constituye predicción sísmica científicamente validada.</p></div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const map=L.map('map').setView([-33.45,-70.65],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);let D,layers=[];const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=x=>new Date(x).toLocaleString('es-CL');
function inspect(code){let r=D.results.find(x=>x.code===code),p=r.prediction,m=r.match;let h=`<h3>${esc(p.code)} · ${esc(p.group_name)}</h3><b>${r.status}</b><br>M${p.mag_min}–M${p.mag_max} · radio ${r.radius} km<br>${esc(p.place)}<br>${p.date_start} → ${p.date_end}`;if(m){let e=m.event;h+=`<hr><b>Sismo CSN:</b> M${Number(e.magnitude).toFixed(1)}<br>${esc(e.place)}<br>${fmt(e.occurred_at)}<br><b>Distancia:</b> ${m.distance_km.toFixed(1)} / ${r.radius} km<br><b>Δ magnitud:</b> ${m.delta_mag.toFixed(2)}<br>Tiempo ${m.time_ok?'✅':'❌'} · Magnitud ${m.mag_ok?'✅':'❌'} · Ubicación ${m.geo_ok?'✅':'❌'}${e.source_url?`<br><a target="_blank" href="${esc(e.source_url)}">Informe oficial CSN ↗</a>`:''}`};document.getElementById('inspect').innerHTML=h}
function draw(){layers.forEach(x=>map.removeLayer(x));layers=[];let ia=document.getElementById('ia').value,st=document.getElementById('st').value,only=document.getElementById('only').checked,rad=document.getElementById('rad').checked,lin=document.getElementById('lin').checked,rs=D.results.filter(r=>(!ia||r.group===ia)&&(!st||r.status===st)&&(!only||r.status==='ACERTADA')),ids=new Set(rs.filter(r=>r.match).map(r=>String(r.match.event.source_id)));D.events.forEach(e=>{if(only&&!ids.has(String(e.source_id)))return;let x=L.circleMarker([e.latitude,e.longitude],{radius:4,color:'#ff667a'}).bindPopup(`CSN M${e.magnitude}<br>${esc(e.place)}<br>${fmt(e.occurred_at)}`).addTo(map);layers.push(x)});rs.forEach(r=>{let p=r.prediction,c=r.status==='ACERTADA'?'#56e39f':r.status==='PENDIENTE'?'#42d9ff':'#8793a1',x=L.circleMarker([p.latitude,p.longitude],{radius:7,color:c}).addTo(map);x.on('click',()=>inspect(r.code));layers.push(x);if(rad)layers.push(L.circle([p.latitude,p.longitude],{radius:r.radius*1000,color:c,weight:1,fillOpacity:.03}).addTo(map));if(lin&&r.match){let e=r.match.event;layers.push(L.polyline([[p.latitude,p.longitude],[e.latitude,e.longitude]],{color:'#56e39f',dashArray:'5,6'}).addTo(map))}})}
async function load(){D=await fetch('/api/dashboard',{cache:'no-store'}).then(x=>x.json());for(let k of ['events','hits','pending','misses'])document.getElementById(k).textContent=D.stats[k];pred.textContent=D.stats.predictions;corrs.textContent=D.stats.correlations;hist.textContent=D.stats.history_records;rank.innerHTML=D.ranking.map((x,i)=>`<tr><td>${i<3?['🥇','🥈','🥉'][i]:'▫️'} ${esc(x.group)}</td><td>${x.hits}</td><td>${x.misses}</td><td>${x.pending}</td><td>${x.accuracy==null?'—':x.accuracy+'%'}</td></tr>`).join('');ia.innerHTML='<option value="">Todas las IA</option>'+[...new Set(D.results.map(x=>x.group))].map(x=>`<option>${esc(x)}</option>`).join('');results.innerHTML=D.results.map(r=>`<div class="result" data-code="${esc(r.code)}"><b>${r.status==='ACERTADA'?'🟢':r.status==='PENDIENTE'?'🟡':'⚫'} ${esc(r.code)}</b> · ${esc(r.group)}<br><span class="muted">M${r.prediction.mag_min}–M${r.prediction.mag_max} · ${r.radius} km${r.match?' · ↔ M'+Number(r.match.event.magnitude).toFixed(1)+' a '+r.match.distance_km.toFixed(1)+' km':''}</span></div>`).join('');document.querySelectorAll('.result').forEach(x=>x.onclick=()=>inspect(x.dataset.code));quakes.innerHTML=D.events.slice(0,30).map(e=>`<tr><td>${fmt(e.occurred_at)}</td><td>${esc(e.place)}</td><td>M${Number(e.magnitude).toFixed(1)}</td></tr>`).join('');draw()}
['ia','st','rad','lin','only'].forEach(x=>document.getElementById(x).addEventListener('change',draw));load();setInterval(load,60000);
</script></body></html>'''
@app.get('/')
def home():return render_template_string(HTML)
@app.get('/health')
def health():return {'ok':True,'db':DB_PATH,'evaluator':'shared-v1.5'}
def run_dashboard():app.run(host='0.0.0.0',port=int(os.getenv('PORT','8080')),debug=False,use_reloader=False)
